import { useUser } from '@/context/context'
import Head from 'next/head'

export default function Home() {

  const {user, setUser} = useUser()

  console.log(user)

  return (
    <>
      <Head>
        <title>InvestMatch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1>Home</h1>
      </main>
    </>
  )
}
