import Header from '@/components/header/Header'
import { useUser } from '@/context/context'
import Head from 'next/head'
import { DashboardHeaderCss, ShowProjectsCss } from './style'

export default function Home() {

  const { user, setUser } = useUser()

  console.log(user)

  return (
    <>
      <Head>
        <title>InvestMatch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <ShowProjectsCss >
        <DashboardHeaderCss>
          <h1>Projetos!</h1>
          {user?.type === 'company' ? <button>Novo projeto +</button> : ''}
        </DashboardHeaderCss>



      </ShowProjectsCss>
    </>
  )
}
